# Copilot Agent Environment Setup Steps
# This file instructs GitHub Copilot on how to set up the development environment
# Reference: https://docs.github.com/en/copilot/how-tos/use-copilot-agents/coding-agent/customize-the-agent-environment

# Environment Configuration
name: Jekyll Site Development Environment

# Base Environment
# The development environment should mirror the Dockerfile configuration
base:
  image: ruby:3.3.0-bookworm
  description: Ruby-based Jekyll static site generator environment

# Required System Dependencies
system_dependencies:
  - name: GitHub CLI
    description: Required for gh-tt workflow integration
    install_command: |
      curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
      chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
      echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
      apt-get update && apt-get install gh -y

  - name: Node.js and npm
    description: Required for cspell and markdownlint-cli2
    note: Should be available in the environment for linting tasks

  - name: Locale (UTF-8)
    description: Liquid/Jekyll requires UTF-8 for BOM character support
    install_command: |
      apt-get install -y locales
      echo "en_US UTF-8" > /etc/locale.gen
      locale-gen en_US UTF-8
    environment_vars:
      LANG: en_US.UTF-8
      LANGUAGE: en_US:en
      LC_CTYPE: en_US.UTF-8
      LC_ALL: en_US.UTF-8

# Ruby Dependencies
ruby_dependencies:
  install_command: bundle install
  description: Install all gems specified in Gemfile (Jekyll, html-proofer, rake, etc.)
  note: The Gemfile.lock ensures consistent versions

# Node.js Dependencies
node_dependencies:
  packages:
    - cspell
    - markdownlint-cli2
    - "@cspell/dict-da-dk"
  install_command: npm install -g cspell markdownlint-cli2 @cspell/dict-da-dk

# Setup Steps (in order)
setup_steps:
  - step: 1
    name: Install System Dependencies
    description: Install GitHub CLI and locale support
    critical: true
    
  - step: 2
    name: Install Ruby Gems
    command: bundle install
    description: Install Jekyll and all required Ruby gems
    critical: true
    working_directory: /home/runner/work/renogfri.dk/renogfri.dk
    
  - step: 3
    name: Install Node.js Tools
    command: npm install -g cspell markdownlint-cli2 @cspell/dict-da-dk
    description: Install linting tools for markdown and spelling
    critical: true
    note: These are required for the pre-commit hook

  - step: 4
    name: Configure Git Hooks
    command: git config core.hooksPath .githooks
    description: Enable the pre-commit hook for validation
    critical: true

# Validation Command
validation:
  command: .githooks/pre-commit
  description: Run all pre-commit checks to validate the environment
  success_criteria: Exit code 0
  note: This runs Jekyll build, HTML proofer, cspell, and markdownlint checks

# Build Commands
build:
  development:
    command: bundle exec rake jekyll:serve
    description: Start development server with live reload on port 4000
    port: 4000
    
  production:
    command: bundle exec rake build
    description: Build the Jekyll site for production (_site directory)
    output_directory: _site

# Testing Commands
testing:
  pre_commit:
    command: .githooks/pre-commit
    description: Run all validation checks (spelling, markdown lint, Jekyll build, HTML proofer)
    
  internal_links:
    command: bundle exec rake proofer:check
    description: Validate internal HTML links only
    
  external_links:
    command: bundle exec rake proofer:check_external
    description: Validate both internal and external HTML links

# Important Notes
notes:
  - The project uses Jekyll 4.3.3 with source in src/ directory
  - Generated site goes to _site/ directory (not version controlled)
  - The gh-tt CLI extension is used instead of traditional PRs
  - When working on copilot/* branches, no issue number needs to be extracted from the branch name
  - Success criteria: .githooks/pre-commit must pass with exit code 0
